name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: [self-hosted,cml,gpu]
    steps:
      - uses: actions/checkout@v2
      - name: run_cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo '```' > report.md
          nvidia-smi >> report.md
          echo '```' >> report.md
          
          cml-send-comment report.md
